function p = pluto_initialize()
    p = struct();

    p.centerFreq = 1.5e9;
    p.basebandFs = 320e3;

    p.txGain = -10;
    p.rxGain = 30;

    p.samplesPerFrame = 200000;

    p.tx = sdrtx("Pluto", ...
        "CenterFrequency",    p.centerFreq, ...
        "BasebandSampleRate", p.basebandFs, ...
        "Gain",               p.txGain);

    p.rx = sdrrx("Pluto", ...
        "CenterFrequency",    p.centerFreq, ...
        "BasebandSampleRate", p.basebandFs, ...
        "SamplesPerFrame",    p.samplesPerFrame, ...
        "OutputDataType",     "single", ...
        "GainSource",         "Manual", ...
        "Gain",               p.rxGain);

    p.tx.ShowAdvancedProperties = true;
end
